### ISSUE TITLE
Ideas for things to do later... maybe... hopefully... who knows

### ISSUE THREAD

**Issue by thecoshman** [LoungeCPP/Tatsoryk#18]
- [ ] Domain to host game
- [ ] Gateway server to accept initial connection then offload to actual game servers
- [ ] Support multiple games running at the same time
- [ ] Upgrades
- [ ] Persistent accounts
- [ ] Maps
- [ ] Hats
- [ ] Obstacles
- [ ] Interactive elements (ie exploding barrel)
- [ ] Alternate weapons
- [ ] Background music
- [ ] Sound fx
- [ ] Agar.io style global game system
- [ ] In-game chat
- [ ] Native client
- [ ] Steam (vOv dream big guys)
- [ ] Decent logging that isn't just dumping to console.log
- [ ] Most (all?) of the game settings loaded rather than hard-coded
- [ ] Have a way for settings to be reloaded without having to actually restart the server (let current games finish with what ever settings they started with)
- [ ] Start games as a proper round, rather than just as soon as people join
- [ ] Dual-stick controller support
- [ ] Squares for players (as per spec)
### [V1](https://github.com/LoungeCPP/Tatsoryk/milestones/V1)
- [ ] names for players (#26)
- [ ] Track scores in a game (#27)
- [ ] Have a way to win a game (#28)

---

Just edit to add more ideas.
If taking an idea a creating a proper issue, update this to with link to the issue you created and place it under the appropriate milestone.
